version: '3.8'

services:
  springboot-app:
    image: ihwijae/workcongw
    ports:
      - "8080:8080"
    restart: always

    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    container_name: workcongw-app

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
#      - /home/ec2-user/default.conf:/etc/nginx/conf.d/default.conf
      - /Users/ihwijae/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - springboot-app
    container_name: workcongw-nginx

networks:
 app-network:
  driver: bridge